create login page
Bluewizzy1/BlitzCount pull request #5
Opened 2024-01-01 12:27 UTC by Bluewizzy1

create login page

2024-01-03 22:53 UTC, tiammui requested changes

2024-01-03 22:53 UTC, tiammui commented on src/App.js
> +    <div className="bg-[#D2D2D2] w-full max-w-[fixed-width] px-[30px]">
The **_fixed-width_** here should have being the container width in pixels e.g 100px, 20px etc

2024-01-03 22:53 UTC, tiammui commented on src/pages/Login.js
We should go with this for now, but this file will be worked on later
It looks good, but we'll face problem when we want to integrate functionalities later

2024-01-07 09:56 UTC, Bluewizzy1 commented
What is the cause for the potential challenges

On Wed, 3 Jan 2024, 11:53 pm Tiamiyu Muizz, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/App.js
> <https://github.com/Bluewizzy1/BlitzCount/pull/5#discussion_r1441057119>:
>
> >  import Dashboard from "./pages/Dashboard";
>  import Topbar from "./components/Topbar";
>
>  function App() {
>    return (
> -    <div className="bg-[#D2D2D2]">
> +    <div className="bg-[#D2D2D2] w-full max-w-[fixed-width] px-[30px]">
>
> The *fixed-width* here should have being the container width in pixels
> e.g 100px, 20px etc
> ------------------------------
>
> On src/pages/Login.js
> <https://github.com/Bluewizzy1/BlitzCount/pull/5#discussion_r1441061003>:
>
> We should go with this for now, but this file will be worked on later
> It looks good, but we'll face problem when we want to integrate
> functionalities later
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bluewizzy1/BlitzCount/pull/5#pullrequestreview-1803190079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A55DXN63WKN6RBTHKMRTAFLYMXOQLAVCNFSM6AAAAABBI7WIZOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBTGE4TAMBXHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-08 22:44 UTC, tiammui commented
We can discuss the potential issue on a call 🙂

I requested some changes on some part of the code

Please action it so that this PR can be merged

2024-01-10 11:02 UTC, merged